# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_aKSjDDeDmDGcCu5FV94zxJXz6FUuCK
"""

# Commented out IPython magic to ensure Python compatibility.
%pip install streamlit

# app.py

import streamlit as st
import pandas as pd
import requests
from bs4 import BeautifulSoup
import io

@st.cache_data
def obtener_tabla_bogota():
    # Paso 1: Obtener enlace del archivo Excel
    url = "https://www.dane.gov.co/index.php/estadisticas-por-tema/agropecuario/sistema-de-informacion-de-precios-sipsa/componente-precios-mayoristas"
    resp = requests.get(url)
    soup = BeautifulSoup(resp.content, 'html.parser')
    enlaces = soup.find_all('a', href=True)

    enlace_excel = next((f"https://www.dane.gov.co{a['href']}" for a in enlaces if a.get_text().strip().lower() == 'anexo'), None)
    if not enlace_excel:
        return pd.DataFrame({"Error": ["No se encontró el archivo 'Anexo' en la página del DANE."]})

    # Paso 2: Descargar Excel y procesar
    resp = requests.get(enlace_excel)
    df_raw = pd.read_excel(io.BytesIO(resp.content), header=None)

    columnas_combinadas = df_raw.iloc[1].fillna(method='ffill') + " - " + df_raw.iloc[2].fillna('')
    df_raw.columns = ['Producto'] + list(columnas_combinadas[1:])
    df_limpio = df_raw.iloc[4:].copy()

    columnas_bogota = [col for col in df_limpio.columns if col.startswith('Bogotá, Corabastos')]
    if not columnas_bogota:
        return pd.DataFrame({"Error": ["No se encontraron columnas de Bogotá."]})

    df_bogota = df_limpio[['Producto'] + columnas_bogota].copy()
    df_bogota.columns = ['Producto', 'Precio ($/kg)', 'Variación %']
    df_bogota['Precio ($/kg)'] = pd.to_numeric(df_bogota['Precio ($/kg)'], errors='coerce')
    df_bogota['Variación %'] = pd.to_numeric(df_bogota['Variación %'], errors='coerce')
    df_bogota = df_bogota.dropna().reset_index(drop=True)

    return df_bogota

# === INTERFAZ ===
st.set_page_config(page_title="Precios SIPSA Bogotá", layout="centered")
st.title("📊 Precios Mayoristas - Bogotá (SIPSA)")
st.caption("Datos extraídos automáticamente desde el DANE (archivo 'Anexo')")

if st.button("🔄 Actualizar tabla"):
    df = obtener_tabla_bogota()
    st.dataframe(df)

    # Botón para descargar CSV
    csv = df.to_csv(index=False).encode('utf-8')
    st.download_button("📥 Descargar como CSV", data=csv, file_name="precios_bogota.csv", mime='text/csv')

